// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEOA6oB_ElXVNvYNXJnWxe70M82ugfQ2A',
    appId: '1:11879661373:android:e1fe3bbddaa1964b0dcf54',
    messagingSenderId: '11879661373',
    projectId: 'laptopstore-d6390',
    storageBucket: 'laptopstore-d6390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_EQ22JMIDkDQxvdRegeOGxnZRkONPSgM',
    appId: '1:11879661373:ios:c46158abba4665d70dcf54',
    messagingSenderId: '11879661373',
    projectId: 'laptopstore-d6390',
    storageBucket: 'laptopstore-d6390.appspot.com',
    androidClientId: '11879661373-fh3d81ulkaqjacb0mdac2u36d1a5l97k.apps.googleusercontent.com',
    iosClientId: '11879661373-r191o4f98a4r9cbeabn40f9ui4a9331k.apps.googleusercontent.com',
    iosBundleId: 'com.example.laptopShop',
  );
}
